### ISSUE TITLE
Basic question on hows and whys of implementing this module

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2-Plugin-Ajax#6]
I don't know much about the technical underpinnings of ajax and I am new to Dancer2 so forgive my ignorance with this question.

So I've got this route and subroutine which handles an ajax post request sent by some javascript and then sends back the appropriate message in some json:

```
Package MyApp::Supplement;
use JSON::MaybeXS qw(:all);
use Dancer2 appname => MyApp;

post '/form_processor' => sub {
  my $s_msg = 'Login successful';
  my $f_msg = 'Failed!';
  $login_succeeded = # code to figure out if login succeeded 
  _return_json($login_succeeded, {message => $s_msg}, {message => $f_msg});
};

sub _return_json {
  my $success = shift;
  my $success_data = shift || {};
  my $failure_data = shift || $success_data;

  my %data = $success ? %$success_data : %$failure_data;
  $data{result} = $success ? JSON->true : JSON->false;

  encode_json(\%data);
}
```

This is functional and it works. So I have two questions:

1) What advantages do I gain by moving this code to use Dancer2::Plugin::Ajax?

2) And how, exactly, would I convert this script to use the plugin? I made the appropriate changes to my config file and tried following the documentation but did not meet with success. I got json errors. I'm too new to Dancer2 to efficiently print out debug statements to figure out what's going on with the internals. 

I'd be happy to take what I learn here and do a pull request to add to the documentation to help newbs like me. Thank you very much.

**Update**
I had a separate question. If I put the `use JSON::MaybeXS qw(:all);` line after the `use Dancer2;` line, I get parameter warnings. Clearly, I'm not using the `JSON` module as Dancer2 expects or intends.

**Comment by sdondley** [comment]
OK, so I've been playing around with this and did some debugging. I got the plugin to work with my javascript. I'm not sure, but I may have found a bug (more likely, it's me not knowing how to properly use Dancer2). When I set the `content_type` to `application/json`, the json that is returned back to the javascript looks like this:

`{result: 1, message: "Login successful"}`

I got things to work by changing the `content_type` to `text/html` for the plugin setting which resulted in this json getting sent back to the javascript after getting encoded:

`{"result": 1, "message": "Login successful"}`

Note the quotes around the keys. 

And here are the subroutines that work with the `ajax` route:

```
ajax '/ajax_test' => sub {
  my $s_msg = 'Login successful';
  my $f_msg = 'Failed!';
  my $data = _return_json(1, {message => $s_msg}, {message => $f_msg});
  my $json = encode_json($data);
  return $json;

};

sub _return_json {
  my $success = shift;
  my $success_data = shift || {};
  my $failure_data = shift || $success_data;

  my %data = $success ? %$success_data : %$failure_data;
  $data{result} = $success ? 1 : 0;
  return \%data;
}
```

**Comment by cromedome** [comment]
You might want to look at the send_as keyword (https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod#send_as). It might make some of what you were trying to do easier!

**Comment by xsawyerx** [comment]
The warning you are getting is because you are loading both `Dancer2` and `JSON::MaybeXS`. They are both providing you with a `to_json` and `from_json` functions, but they have different prototypes. Perl detects that and says "Hey, these might not be the same functions. Are you sure this is correct?" (Of course, these aren't Perl's words, but that's what it means to say.)

`Dancer2::Plugin::Ajax` does the following:

* Create a route with the path for both `get` and `post`
* Checks during a request that the request contains the right headers for AJAX, namely the header `X-Requested-With` exists and set to `XMLHttpRequest`.
* The route sets the response header 'content-type' to either `text/xml` or whatever you have defined in `content_type` settings of the plugin.
* Serves the content of your route using the header above and without a layout.

The reason why you might want to use it is if you don't want to write the above for your code.
